[package]
name = "cuckoomap"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
ahash = "0.7.4"
roaring = "0.8.0"
